### ISSUE TITLE
Add examesh.de/en/

### ISSUE THREAD

**Issue by dhafner** [zszazi/Deep-learning-in-cloud#27]
Free 15 mins trial; pre-built Docker images (including CUDA, PyTorch, Jupyter, ...); Data Centers deployed in renewable energy power plants; V100 32 GB GPU; straight Docker layer

**Comment by InCogNiTo124** [comment]
@dhafner please provide more detailed pricing info and you'll be added. 15min free trial is not enough

**Comment by dhafner** [comment]
@InCogNiTo124 Sure! The hourly price is 1.86 USD per AI Instance with the following ressources: Tesla V100 32 GB; 12 cores (each with 2 threads), 204 GB RAM, 870 GB NVMe SSD.

Special discounts for long-term bookings are available. Public research is supported free of charge.

**Comment by zszazi** [comment]
Thanks dhafner for the info 

@InCogNiTo124 Updated the PR , merging it now

**Comment by thisserand13** [comment]
@dhafner Could you give me more information about the public research support? I couldn't find anything about it on the website. I am just starting to work on my master thesis. Since part of it is comparing different neural network architectures, I am looking at suitable cloud providers.

Thanks in advance!

**Comment by dhafner** [comment]
Please contact me via mail: d.hafner@examesh.de
Feel free to let us talk about your request and what exactly you have in mind!
